parameters:
  - name: actionGroups
    type: object
    default: []
  - name: enableProduction
    type: boolean
    default: false
  - name: runReviewStage
    type: boolean
    default: true
  - name: drInvocation
    type: boolean
    default: false
  - name: skip_environments
    type: object
    default:
      dev: false
      qa: false
      ppr: false

resources:
  repositories:
    - repository: PipelineDispatcher
      type: github
      endpoint: wesley-trust
      name: wesley-trust/pipeline-dispatcher
      ref: "refs/heads/feature/default-settings"
      #ref: "refs/heads/main"

extends:
  template: /templates/pipeline-defaults.yml@PipelineDispatcher
  parameters:
    ${{ each parameter in parameters }}:
      ${{ parameter.key }}: ${{ parameter.value }}
    # Default Overrides
    defaultPool:
      vmImage: "ubuntu-latest"
    serviceConnection: serviceConnection
    environments:
      - name: dev
        class: development
        dependsOnSecondaryRegions: false
        primaryRegion: weu
        secondaryRegions:
          - neu
        drRegion: neu
        allowedBranches:
          - "*"
        pool:
          vmImage: "ubuntu-latest"
        skipEnvironment: ${{ parameters.skip_environments.dev }}
        poolRegionDemand: false
      # - name: qa
      #   class: test
      #   dependsOnSecondaryRegions: false
      #   primaryRegion: weu
      #   allowedBranches:
      #     - "main"
      #     - "release/*"
      #   pool:
      #     vmImage: "ubuntu-latest"
      #   skipEnvironment: ${{ parameters.skip_environments.qa }}
      #   poolRegionDemand: false
      - name: ppr
        class: acceptance
        dependsOnSecondaryRegions: false
        primaryRegion: weu
        secondaryRegions:
          - neu
        allowedBranches:
          - "main"
          - "release/*"
        pool:
          vmImage: "ubuntu-latest"
        skipEnvironment: ${{ parameters.skip_environments.ppr }}
        poolRegionDemand: false
      - name: prd
        class: production
        primaryRegion: weu
        secondaryRegions:
          - neu
        drRegion: neu
        allowedBranches:
          - "release/*"
        pool:
          vmImage: "ubuntu-latest"
        poolRegionDemand: true
    variableRoot: vars
    variables:
      includeCommon: true
      includeEnv: true
      includeEnvRegion: false
      includeRegion: true
    variableGroups:
      - "Common-Variables"
    validation:
      enableVariableIncludes: true
    additionalRepositories:
      # - alias: Modules
    keyVault:
      name: ""
      secretsFilter: ""
